-- 1. 품목 새로 생길때 INVENTORY 테이블에 insert 하는 2개 프로시저 만들기 
-- *** 주의 생성할때 프로시저 두개다 만들어야함 한개만하면 바코드 꼬인다***
-- COMPANY 테이블 데이터 추가하는 프로시저
CREATE OR REPLACE PROCEDURE INSERT_COMPANY
(
    INSERT_CODE INT,
    INSERT_COMPANY VARCHAR2
)
IS BEGIN
INSERT INTO COMPANY (CODE,COMPANY) VALUES(INSERT_CODE,INSERT_COMPANY);
END INSERT_COMPANY;
/
-- INVENTORY 테이블 데이터 추가하는 프로시저
CREATE OR REPLACE PROCEDURE INSERT_INVENTORY
(
    INSERT_NAME VARCHAR2,   -- 상품명
    INSERT_CGCODE VARCHAR2, -- 카테고리코드 분류코드
    INSERT_FCODE INT,       -- 상품코드
    INSERT_CNT INT,         -- 재고량
    INSERT_PRICE INT        -- 가격
)
IS BEGIN
INSERT INTO INVENTORY (NAME,CATEGORY_CODE,FOOD_CODE,CNT,PRICE) VALUES(INSERT_NAME,INSERT_CGCODE,INSERT_FCODE,INSERT_CNT,INSERT_PRICE);
END INSERT_INVENTORY;
/