-- 테이블 삭제
DROP TABLE INVENTORY;
DROP TABLE CATEGORY;
DROP TABLE COMPANY;
-- 시퀀스 삭제
DROP SEQUENCE FOOD_BARCODE;         -- 상품코드 시퀀스 
DROP SEQUENCE INVENTORY_BARCODE;    -- 인벤토리 시퀀스
-- 뷰 삭제
DROP VIEW ALL_INFO;
-- INSERT_COMPANY 프로시저 삭제
DROP PROCEDURE INSERT_COMPANY;
-- INSERT_INVENTORY 프로시저 삭제
DROP PROCEDURE INSERT_INVENTORY;
-- UPDATE_CNT 프로시저 삭제
DROP PROCEDURE UPDATE_CNT;
-- UPDATE_PRICE 프로시저 삭제
DROP PROCEDURE UPDATE_PRICE;
-- DELETE_ALL 프로시저 삭제 
DROP PROCEDURE DELETE_ALL;
-- DELETE_INVENTROY_CODE, DELETE_COMPANY_CODE 프로시저 삭제
DROP PROCEDURE DELETE_INVENTROY_CODE;
DROP PROCEDURE DELETE_COMPANY_CODE;
-- 트리거 삭제
DROP TRIGGER ALARM_INSERT_COMPANY;
DROP TRIGGER ALARM_INSERT_INVENTORY;
DROP TRIGGER ALARM_UPDATE_COMPANY;
DROP TRIGGER ALARM_UPDATE_INVENTORY;
DROP TRIGGER ALARM_DELETE_COMPANY;
DROP TRIGGER ALARM_DELETE_INVENTORY;