-- 2. 재고 수정
-- 어떤 상품의 재고를 수정 할 것인가? -> 수정할 재고, 상품 이름 쳐서 재고수정
CREATE OR REPLACE PROCEDURE UPDATE_CNT
(
    UPDATE_CNT INT,
    SEARCH_NAME VARCHAR2
)    
IS BEGIN 
UPDATE INVENTORY SET CNT = UPDATE_CNT WHERE NAME = SEARCH_NAME;
END UPDATE_CNT;
/
-- 3. 가격 수정
-- 어떤 상품 가격을 수정 할 것인가? -> 수정할 가격, 상품 이름 쳐서 가격 수정.
CREATE OR REPLACE PROCEDURE UPDATE_PRICE
(
    UPDATE_PRICE INT,
    SEARCH_NAME VARCHAR2
)
IS BEGIN 
UPDATE INVENTORY SET PRICE = UPDATE_PRICE WHERE NAME = SEARCH_NAME;
END UPDATE_PRICE;
/